# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
